version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M
    networks:
      - portfolio_mongo

  portfolio:
    image: lexkrstn/portfolio
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
      - "443:443"
      - "3000:3000"
    volumes:
      - /opt/portfolio/tls:/opt/portfolio/tls
    environment:
      NODE_ENV: production
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: mongo
      SSR_PORT: 443
      API_EXTERNAL_URL: https://lexkrstn.com:3000
      SSL_KEY: /opt/portfolio/tls/private.key
      SSL_CERT: /opt/portfolio/tls/certificate.crt
      MAIL_USER:
      MAIL_PASSWORD:
    networks:
      - portfolio_mongo

networks:
  portfolio_mongo:
    driver: bridge
