version: '3.5'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.4'
          memory: 200M
    networks:
      - common

  portfolio:
    image: lexkrstn/portfolio
    container_name: portfolio
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - static:/mnt/static
    environment:
      STATIC_DIR: /mnt/static
      STATIC_URL: https://d12d0xnegwp9l0.cloudfront.net
      NODE_ENV: production
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: mongo
      API_EXTERNAL_URL: https://lexkrstn.com
    env_file:
      - .env
    networks:
      - common
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.4'
          memory: 300M
    logging:
      driver: json-file
      options:
        max-size: 50K
        max-file: "10"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - portfolio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static:/var/www/static
    networks:
      - common
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '0.2'
          memory: 100M

  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles: ["certbot"]
    restart: "no"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # certonly: only generate certificate without installing
    # webroot: use our own webserver in this case NGINX
    # w: root directory of webserver for the challenges
    # force-renewal: on repeated run renew certificates
    # email: your email for notifcations
    # d: domain for the certificate (it can be multiple -d)
    # agree-tos: agree the terms of service automatically
    command: >
      certonly --webroot --agree-tos --force-renewal
      -w /var/www/certbot
      --email lexkrtn@gmail.com
      -d lexkrstn.com

networks:
  common:
    driver: bridge

volumes:
  static:
  mongo:
