version: '1.0'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  portfolio:
    image: lexkrstn/portfolio
    restart: always
    ports:
      - 80:80
      - 3000:3000
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: mongo
      API_EXTERNAL_URL: http://3.145.156.98:3000
