const skills = [
  {
    name: 'TypeScript',
    icon: 'typescript.svg',
    masteryYear: 2015,
    note: 'Whenever possible, I program both the backend and the frontend in TS.',
    group: 'basic',
    level: 5,
    weight: 0,
  },
  {
    name: 'NodeJS',
    icon: 'nodejs.svg',
    masteryYear: 2015,
    note: 'My favorite environment for server-side development.',
    group: 'basic',
    level: 5,
    weight: 1,
  },
  {
    name: 'PHP',
    icon: 'php.svg',
    masteryYear: 2009,
    note: 'The first website I created was written in this language.',
    group: 'basic',
    level: 5,
    weight: 2,
  },
  {
    name: 'JavaScript',
    icon: 'javascript.svg',
    masteryYear: 2009,
    note: 'The most popular language, so I use it regularly, including ES2021 syntax.',
    group: 'basic',
    level: 5,
    weight: 3,
  },
  {
    name: 'React / Redux',
    icon: 'react.svg',
    masteryYear: 2015,
    note: 'I love it for simlicity. This website is written in this stack, btw.',
    group: 'basic',
    level: 5,
    weight: 4,
  },
  {
    name: 'Vue / Vuex',
    icon: 'vue.svg',
    masteryYear: 2019,
    note: 'Simple but powerful. Wrote a few apps for my customers on Vue.',
    group: 'basic',
    level: 5,
    weight: 5,
  },
  {
    name: 'ExpressJS',
    icon: 'nodejs.svg',
    masteryYear: 2015,
    note: 'Most of my NodeJS apps are written on it and MySQL or PostgreSQL.',
    group: 'basic',
    level: 5,
    weight: 6,
  },
  {
    name: 'MySQL',
    icon: 'mysql.svg',
    masteryYear: 2009,
    note: 'The most popular DBMS and also the first one that I got to know years ago.',
    group: 'basic',
    level: 5,
    weight: 7,
  },
  {
    name: 'PostgreSQL',
    icon: 'postgresql.svg',
    masteryYear: 2015,
    note: 'Most of my own projects use it due to its abundance of features.',
    group: 'basic',
    level: 4,
    weight: 8,
  },
  {
    name: 'Yii 2',
    icon: 'yii.svg',
    masteryYear: 2013,
    note: 'I used to write a lot of PHP sites in the framework as a frelancer.',
    group: 'basic',
    level: 4,
    weight: 9,
  },
  {
    name: 'NestJS',
    icon: 'nestjs.svg',
    masteryYear: 2021,
    note: 'An excellent framework I\'ve been using for all my new projects.',
    group: 'basic',
    level: 4,
    weight: 12,
  },
  {
    name: 'NextJS',
    icon: 'nextjs.svg',
    masteryYear: 2022,
    note: 'The framework that I\'m currently using for one of my pet projects on github.',
    group: 'basic',
    level: 4,
    weight: 12,
  },
  {
    name: 'MongoDB',
    icon: 'mongo.svg',
    masteryYear: 0,
    note: 'Have more of a theretical knowledge. Still, this website is powered by Mongo.',
    group: 'basic',
    level: 2,
    weight: 11,
  },
  {
    name: 'Jest',
    icon: 'jest.svg',
    masteryYear: 2020,
    note: 'I enjoy writing testable code and have some experience with TDD.',
    group: 'basic',
    level: 4,
    weight: 12,
  },
  {
    name: 'Redis',
    icon: 'redis.svg',
    masteryYear: 2021,
    note: 'I have used it for caching and synchronization in a few projects.',
    group: 'basic',
    level: 4,
    weight: 13,
  },
  {
    name: 'Rabbit MQ',
    icon: 'rabbitmq.svg',
    masteryYear: 2021,
    note: 'I\'ve been involved in creating several NodeJS microservices on it.',
    group: 'basic',
    level: 4,
    weight: 14,
  },
  {
    name: 'C++',
    icon: 'cpp.svg',
    masteryYear: 0,
    note: 'Knowledge up to C++11, as originally planned to become a 3d dev.',
    group: 'basic',
    level: 5,
    weight: 15,
  },
  {
    name: 'Go',
    icon: 'go.svg',
    masteryYear: 2022,
    note: 'You can find some opensource projects on my GitHub profile page.',
    group: 'basic',
    level: 3,
    weight: 16,
  },

  {
    name: 'Knex.js / Objection.js',
    icon: 'knexjs.svg',
    masteryYear: 2016,
    note: 'My favorite Query Builder and ORM libraries for Node.js and plain JS.',
    group: 'misc',
    level: 5,
    weight: 0,
  },
  {
    name: 'Styled Components',
    icon: 'styled-components.svg',
    masteryYear: 2017,
    note: 'Used it (as well as CSS Modules) in several projects.',
    group: 'misc',
    level: 5,
    weight: 1,
  },
  {
    name: 'Sass',
    icon: 'sass.svg',
    masteryYear: 2015,
    note: 'Switched from LESS years ago (after Bootstrap did it).',
    group: 'misc',
    level: 5,
    weight: 2,
  },
  {
    name: 'Git',
    icon: 'git.svg',
    masteryYear: 2009,
    note: 'Just using its most common aspects on a day-to-day basis.',
    group: 'misc',
    level: 4,
    weight: 4,
  },
  {
    name: 'Wordpress',
    icon: 'wordpress.svg',
    masteryYear: 2009,
    note: 'Cannot help but mention WP, because I started my freelance career with it.',
    group: 'misc',
    level: 4,
    weight: 5,
  },
  {
    name: 'jQuery',
    icon: 'jquery.svg',
    masteryYear: 2009,
    note: 'Just to mention. Not that it was too unexpected, of cause =)',
    group: 'misc',
    level: 5,
    weight: 7,
  },
  {
    name: 'REST',
    icon: 'rest.svg',
    masteryYear: 2015,
    note: 'Most of my server apps for SPA and microservices are RESTful.',
    group: 'misc',
    level: 5,
    weight: 7,
  },
  {
    name: 'QraphQL',
    icon: 'graphql.svg',
    masteryYear: 2019,
    note: 'Also have some experience working on GraphQL / Apollo projects.',
    group: 'misc',
    level: 3,
    weight: 8,
  },
  {
    name: 'Webpack',
    icon: 'webpack.svg',
    masteryYear: 2015,
    note: 'Got rid of r.js and Gulp when started utilizing it for SPAs.',
    group: 'misc',
    level: 5,
    weight: 9,
  },
  {
    name: 'Mocha + Chai',
    icon: 'mocha.svg',
    masteryYear: 2016,
    note: 'I enjoy writing testable code and have some experience with TDD.',
    group: 'misc',
    level: 4,
    weight: 10,
  },
  {
    name: 'RxJS',
    icon: 'rxjs.svg',
    masteryYear: 2015,
    note: 'I got to know RxJS from Angular and have been using it in React apps too.',
    group: 'misc',
    level: 3,
    weight: 11,
  },
  {
    name: 'Docker',
    icon: 'docker.svg',
    masteryYear: 2019,
    note: 'Most of my apps reside in containers nowadays.',
    group: 'misc',
    level: 4,
    weight: 12,
  },

  {
    name: 'English',
    icon: '',
    masteryYear: 0,
    note: 'Reading - B2, listening - B1, according to <a href="http://efset.org">Efset</a>.',
    group: 'lang',
    level: 5,
    weight: 0,
  },
  {
    name: 'Russian',
    icon: '',
    masteryYear: 0,
    note: 'First language.',
    group: 'lang',
    level: 8,
    weight: 1,
  },
  {
    name: 'Ukrainian',
    icon: '',
    masteryYear: 0,
    note: 'First language.',
    group: 'lang',
    level: 8,
    weight: 0,
  },
];

module.exports = {
  async up(db) {
    await db.collection('skills').insertMany(skills);
  },

  async down(db) {
    await db.collection('skills').deleteMany();
  },
};
