import { from, Observable } from 'rxjs';
import { switchMap, delay, mapTo } from 'rxjs/operators';
import { combineEpics, ofType } from 'redux-observable';
import CONFIG from '../../config';
import { checkFetchResponseStatus } from '../../utils';
import * as actions from './actions';
import * as types from './types';

const requestedEpic = (
  action$: Observable<actions.AllActions>
): Observable<actions.AllActions> => action$.pipe(
  ofType(types.REQUESTED),
  // switchMap((): Observable<Types.PortfolioActionTypes> => {
  //   const promise = fetch(`${CONFIG.apiUrl}/tags`, {
  //       headers: { 'Accept': 'application/json' },
  //     })
  //     .then(checkFetchResponseStatus)
  //     .then(Actions.receiveHashTags)
  //     .catch(error => Actions.failHashTagsRequest(
  //       error.message || 'Connection error',
  //       error.сode,
  //     ));
  //   return from(promise);
  // }),
  delay(1000),
  mapTo(actions.receive([
    {
      id: 1,
      name: 'TypeScript',
      icon: 'typescript.svg',
      masteryYear: 2015,
      note: 'Whenever possible, I program both the backend and the frontend in TS.',
      group: 'basic',
      level: 5,
      weight: 0,
    },
    {
      id: 2,
      name: 'NodeJS',
      icon: 'nodejs.svg',
      masteryYear: 2015,
      note: 'My favorite environment for server-side development.',
      group: 'basic',
      level: 5,
      weight: 1,
    },
    {
      id: 3,
      name: 'PHP',
      icon: 'php.svg',
      masteryYear: 2009,
      note: 'The first website I created was written in this language.',
      group: 'basic',
      level: 5,
      weight: 2,
    },
    {
      id: 4,
      name: 'JavaScript',
      icon: 'javascript.svg',
      masteryYear: 2009,
      note: 'The most popular language, so I use it regularly, including ES2021 syntax.',
      group: 'basic',
      level: 5,
      weight: 3,
    },
    {
      id: 5,
      name: 'React / Redux',
      icon: 'react.svg',
      masteryYear: 2015,
      note: 'I love it for simlicity. This website is written in this stack.',
      group: 'basic',
      level: 5,
      weight: 4,
    },
    {
      id: 6,
      name: 'Vue / Vuex',
      icon: 'vue.svg',
      masteryYear: 2019,
      note: 'Simple but powerful. Wrote a few apps for my customers in it.',
      group: 'basic',
      level: 5,
      weight: 5,
    },
    {
      id: 7,
      name: 'ExpressJS',
      icon: 'nodejs.svg',
      masteryYear: 2015,
      note: 'Most of my NodeJS apps are written in it and MySQL / PostgreSQL.',
      group: 'basic',
      level: 5,
      weight: 6,
    },
    {
      id: 8,
      name: 'MySQL',
      icon: 'mysql.svg',
      masteryYear: 2009,
      note: 'I prefer using the relational database to Mongo even in NodeJS apps.',
      group: 'basic',
      level: 5,
      weight: 7,
    },
    {
      id: 9,
      name: 'PostgreSQL',
      icon: 'postgresql.svg',
      masteryYear: 2015,
      note: 'Most of my own projects use it due to its abundance of features.',
      group: 'basic',
      level: 5,
      weight: 8,
    },
    {
      id: 10,
      name: 'Yii 2',
      icon: 'yii.svg',
      masteryYear: 2013,
      note: 'I used to write a lot of PHP sites in the framework as a frelancer.',
      group: 'basic',
      level: 5,
      weight: 9,
    },
    {
      id: 11,
      name: 'NestJS',
      icon: 'nestjs.svg',
      masteryYear: 2021,
      note: 'An excellent framework I\'ve been using for all my new projects from now on.',
      group: 'basic',
      level: 4,
      weight: 12,
    },
    {
      id: 12,
      name: 'MongoDB',
      icon: 'mongo.svg',
      masteryYear: 0,
      note: 'Theoretical knowledge. Never worked with it in real projects yet.',
      group: 'basic',
      level: 5,
      weight: 11,
    },
    {
      id: 13,
      name: 'C++',
      icon: 'cpp.svg',
      masteryYear: 0,
      note: 'Theoretical knowledge up to C++11, as originally planned to become a 3d dev.',
      group: 'basic',
      level: 5,
      weight: 12,
    },

    {
      id: 100,
      name: 'Knex.js / Objection.js',
      icon: 'knexjs.svg',
      masteryYear: 2012,
      note: 'My favorite Query Builder and ORM libraries for Node.js.',
      group: 'misc',
      level: 5,
      weight: 0,
    },
    {
      id: 101,
      name: 'Styled Components',
      icon: 'styled-components.svg',
      masteryYear: 2017,
      note: 'Most of my NodeJS apps are written in it and MySQL / PostgreSQL.',
      group: 'misc',
      level: 5,
      weight: 1,
    },
    {
      id: 102,
      name: 'Sass',
      icon: 'sass.svg',
      masteryYear: 2015,
      note: 'Switched from LESS years ago (after Bootstrap did it).',
      group: 'misc',
      level: 5,
      weight: 2,
    },
    {
      id: 104,
      name: 'Git',
      icon: 'git.svg',
      masteryYear: 2009,
      note: 'Just using its most common aspects on a day-to-day basis.',
      group: 'misc',
      level: 4,
      weight: 4,
    },
    {
      id: 105,
      name: 'Wordpress',
      icon: 'wordpress.svg',
      masteryYear: 2009,
      note: 'Cannot help but mention WP, because I started my freelance career with it.',
      group: 'misc',
      level: 4,
      weight: 5,
    },
    {
      id: 107,
      name: 'jQuery',
      icon: 'jquery.svg',
      masteryYear: 2009,
      note: 'Just to mention. Not that it was too unexpected, of cause =)',
      group: 'misc',
      level: 5,
      weight: 7,
    },
    {
      id: 108,
      name: 'REST',
      icon: 'rest.svg',
      masteryYear: 2015,
      note: 'Most of my server apps for SPA and microservices are RESTful.',
      group: 'misc',
      level: 5,
      weight: 7,
    },
    {
      id: 109,
      name: 'QraphQL',
      icon: 'graphql.svg',
      masteryYear: 2019,
      note: 'I happened to work with GraphQL projects only twice in my entire career.',
      group: 'misc',
      level: 3,
      weight: 8,
    },
    {
      id: 110,
      name: 'Webpack',
      icon: 'webpack.svg',
      masteryYear: 2015,
      note: 'Got rid of r.js and Gulp when started to use it for my SPAs.',
      group: 'misc',
      level: 5,
      weight: 9,
    },
    {
      id: 111,
      name: 'Mocha + Chai',
      icon: 'mocha.svg',
      masteryYear: 2016,
      note: 'Rarely does the project get tested in freelance, but my own ones do.',
      group: 'misc',
      level: 5,
      weight: 10,
    },
    {
      id: 112,
      name: 'RxJS',
      icon: 'rxjs.svg',
      masteryYear: 2015,
      note: 'I got to know RxJS from Angular and have been using it even in React apps.',
      group: 'misc',
      level: 5,
      weight: 11,
    },
    {
      id: 114,
      name: 'Docker',
      icon: 'docker.svg',
      masteryYear: 2019,
      note: 'Basic knowledge. Built a few microservices wrapped in its containers.',
      group: 'misc',
      level: 5,
      weight: 12,
    },

    {
      id: 201,
      name: 'English',
      icon: '',
      masteryYear: 0,
      note: 'Reading - B2, listening - B1, according to <a href="http://efset.org">Efset</a>. The speaking skills mark would be somewhat lower.',
      group: 'lang',
      level: 5,
      weight: 0,
    },
    {
      id: 202,
      name: 'Russian',
      icon: '',
      masteryYear: 0,
      note: 'First language.',
      group: 'lang',
      level: 8,
      weight: 1,
    },
    {
      id: 203,
      name: 'Ukrainian',
      icon: '',
      masteryYear: 0,
      note: 'First language.',
      group: 'lang',
      level: 8,
      weight: 0,
    },
  ])),
);

export default combineEpics(
  requestedEpic,
);
